default: &default
  authn_header: <%= ENV["AUTHN_HEADER"].presence || "X-Auth-Token" %>
  authn_token: <%= ENV["AUTHN_TOKEN"].to_s.strip %>
  authz_header: <%= ENV["AUTHZ_HEADER"].presence || "X-Auth-User" %>
  authz_token: <%= ENV["AUTHZ_TOKEN"].to_s.strip %>

development:
  <<: *default
  secret_key_base: 54663e3c477de43bd117ddbf1798951ba5cf692dbf8327bb21f341048f04ea95344eed6c8763625a39648bfc2583f128b296bcb3a4756ef8160e483664efcb0b

test:
  secret_key_base: 334f81f95f09f01e58b950ff5e5f9cd914cc151c186358d509d44520d4a1fb46c5af2dea39ed06a897c7cfe58b9c93316fa6c81081b7a30f5e43d271ca2aec0d

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"].presence || (0...128).map { [*'0'..'9', *'a'..'z', *'A'..'Z'].sample }.join %>
